---
# default carbon schema

type: map
allowempty: True
mapping:
  name:
    required: True
    type: str
  description:
    required: False
    type: str
  resource_check:
    type: seq
    sequence:
      - type: str
  include:
    required: False
    type: any

  provision:
    required: False
    sequence:
      - type: map
        allowempty: True
        matching-rule: any
        mapping:
          name:
            required: True
            type: str
          description:
            type: str
          ip_address:
            required: False
            type: any
          provisioner:
            type: str
          provider:
            allowempty: True
            required: False
            type: map
          ansible_params:
            type: map
            allowempty: True
          metadata:
            allowempty: True
            type: map
          regex;(role|groups):
            required: False
            type: any
            func: type_str_list
          regex;(.*):
            required: False
            type: any
            func: type_str_list

  orchestrate:
    sequence:
      - type: map
        allowempty: True
        mapping:
          name:
            required: True
            type: str
          description:
            type: str
          orchestrator:
            type: str
            func: valid_orchestrator
          hosts:
            required: True
            type: any
            func: type_str_list
          ansible_script:
            type: bool
          ansible_options:
            allowempty: True
            type: map
          ansible_galaxy_options:
            allowempty: True
            type: map

  execute:
    sequence:
      - type: map
        allowempty: True
        func: valid_execute_types
        mapping:
          name:
            required: True
            type: str
          description:
            type: str
          executor:
            required: True
            type: str
          hosts:
            required: True
            type: any
            func: type_str_list
          git:
            allowempty: True
            type: seq
            sequence:
              - type: map
                mapping:
                  repo:
                    required: True
                    type: str
                  version:
                    required: True
                    type: str
                  dest:
                    required: True
                    type: str
          shell:
            allowempty: True
            type: seq
            sequence:
              - type: map
                mapping:
                  chdir:
                    type: str
                  ignore_rc:
                    type: bool
                  valid_rc:
                    type: any
                    func: type_int_list
                  command:
                    required: True
                    type: str
          script:
            allowempty: True
            type: seq
            sequence:
              - type: map
                mapping:
                  chdir:
                    type: str
                  ignore_rc:
                    type: bool
                  valid_rc:
                    type: any
                    func: type_int_list
                  name:
                    required: True
                    type: str
          playbook:
            allowempty: True
            type: seq
            sequence:
              - type: map
                mapping:
                  chdir:
                    type: str
                  ignore_rc:
                    type: bool
                  name:
                    required: True
                    type: str
          artifacts:
            type: any
            func: type_str_list
          ignore_rc:
            type: bool

  report:
    sequence:
    - type: map
      allowempty: True
      mapping:
        name:
          required: True
          type: any
        description:
          type: str
        executes:
          type: any
          func: type_str_list
          required: False