---

- hosts: "{{ hosts }}"
  vars:
    nfs_exports: "{{ nfs_exports }}" 

  tasks:
    - name: Preparing NFS Storage
      package:
        name: nfs-utils
        state: present
      register: result
      until: result.rc == 0
      retries: 3
      delay: 15

    - name: Setup NFS Storage
      shell: chkconfig --add rpcbind; chkconfig --add nfs; chkconfig rpcbind on; chkconfig nfs on


    - name: Start NFS rpcbind Service
      service:
        name: rpcbind
        state: started

    - name: Start NFS Service
      service:
        name: nfs
        state: started

    - name: Preparing NFS Storage Directies
      file:
        path: "{{ item }}"
        state: directory
        mode: 0755
      loop:
        "{{ nfs_exports }}"

    - name: Preparing NFS Storage /etc/exports config file
      shell: echo "{{ item }} *(rw)" >> /etc/exports
      loop:
        "{{ nfs_exports }}"

    - name: NFS Storage Reload
      service:
        name: nfs
        state: reloaded

    - name: Configure NFS Directory permissions
      file:
        path: "{{ item }}"
        owner: 36:36
        recurse: yes
      loop:
        "{{ nfs_exports }}"

