---

- hosts: "{{ hosts }}"

  tasks:
    - name: Subscribe to RHN network using subscription_manager Auto
      redhat_subscription:
        state: present
        server_hostname: "{{ rhn_hostname | default('subscription.rhsm.redhat.com') }}"
        username: "{{ rhn_user }}"
        password: "{{ rhn_password }}"
        auto_attach: "{{ auto }}"
      register: result
      until: result.changed or result.msg is defined and result.msg.find('System already registered.') != -1
      retries: 3
      delay: 20
      when: auto is defined

    - name: Subscribe to RHN network using subscription_manager and pool ids
      redhat_subscription:
        state: present
        server_hostname: "{{ rhn_hostname | default('subscription.rhsm.redhat.com') }}"
        username: "{{ rhn_user }}"
        password: "{{ rhn_password }}"
        pool_ids: "{{ pool_ids }}"
      register: result
      until: result.changed or result.msg is defined and result.msg.find('System already registered.') != -1
      retries: 3
      delay: 20
      when: pool_ids is defined

