#!/usr/bin/env python
# -*- coding: utf-8 -*-
import os
from subprocess import check_call
import shutil

_dname = os.path.dirname

REPO_ROOT = _dname(_dname(os.path.abspath(__file__)))
os.chdir(REPO_ROOT)


def run(command):
    return check_call(command, shell=True)

# install development libraries
run('pip install -r requirements.txt')
# install test libraries
run('pip install nose tox coverage flake8')
# clean distribution
if os.path.isdir('dist') and os.listdir('dist'):
    shutil.rmtree('dist')
run('python setup.py bdist_wheel')
wheel_dist = os.listdir('dist')[0]
# install distribution
run('pip install %s' % (os.path.join('dist', wheel_dist)))
