#!/usr/bin/env python
# -*- coding: utf-8 -*-
from subprocess import check_call
from sys import platform, version_info

import os

_dname = os.path.dirname
_pyver = 'cover/integration/py%s%s' % (version_info.major, version_info.minor)

REPO_ROOT = _dname(_dname(os.path.abspath(__file__)))
os.chdir(os.path.join(REPO_ROOT, 'tests'))

# Create nosetests coverage folder
if not os.path.isdir(_pyver):
    os.makedirs(_pyver)


def run(command):
    return check_call(command, shell=True)

if platform == "darwin":
    # set encoding as tox on mac loses the default encoding parameters
    # and nosetests complains of unknown encoding.
    os.environ["LANG"] = "en_US"
    os.environ["LC_COLLATE"] = "UTF-8"
    os.environ["LC_CTYPE"] = "UTF-8"
    os.environ["LC_MESSAGES"] = "UTF-8"
    os.environ["LC_MONETARY"] = "UTF-8"
    os.environ["LC_TIME"] = "UTF-8"

run('nosetests --with-coverage --cover-erase --cover-package carbon '
    '--with-xunit --xunit-file {0}/nosetests.xml --cover-xml '
    '--cover-xml-file {0}/coverage.xml --cover-html --cover-html-dir {0} -v '
    '--disabledoc ./integration/ ./functional/'.format(_pyver))
