# Configure and start up firewall (iptables)
#   Input: fw_cmds - settings for firewall

# Configure iptables 
- name: configure iptables
  shell: iptables {{ item }}
  with_items: fw_cmds
  when: fw_cmds
  register: result

# Flush iptables when no configuration
- name: flush iptables on no configure
  shell: iptables --flush
  when: result|skipped

# Save iptables
- name: iptables save
  shell: service iptables save

# Set on. So to start on boot 
- name: iptables on
  shell: chkconfig iptables on

# Start
- name: iptables restart
  service: name=iptables state=started

