User's Guide
------------

This document starts with some background information about Carbon,
then go on a step-by-step instructions to create and run scenarios,
extend the framework and collaborate with the project, if you wish.

.. toctree::
    :maxdepth: 2

    introduction
    overview
    installation
    quickstart
    components

Carbon Services
---------------

-   `Carbon Services documentation <services/index.html>`_

Carbon Client
-------------

-   `Carbon Client documentation <client/index.html>`_


Additional Notes
----------------

Development instructions, design notes and changelog.

.. toctree::
    :maxdepth: 2

    development
    design
    changelog
