.. toctree::
    :maxdepth: 2
    :caption: Installation & Configuration
    :hidden:

    users/install
    users/configuration

.. toctree::
    :maxdepth: 2
    :caption: Using Carbon
    :hidden:

    users/index

.. toctree::
    :maxdepth: 2
    :caption: Carbon Development
    :hidden:

    developers/index

.. toctree::
    :maxdepth: 1
    :caption: References
    :hidden:

    glossary
    changelog
    contact
