# sample ansible.cfg
# [defaults]
# inventory = inventory
# driver and client should be the names of the host group
# i.e.
# [driver]
# driver
# [client]
# client
# ansible-playbook access_multiple_hosts.yml -e "hosts=driver machine=client"
---

# play 1: gather facts for all inventory hosts
- hosts: all

# play 2: get information regarding another inventory host over the one
# specified to run this play on
- hosts: "{{ hosts }}"
  vars:
    # override this variable with the host you wish to fetch information for
    machine: changeme

  tasks:
    - name: System {{ hosts }} IPv4 address
      debug:
        msg: >
          {{ hostvars[inventory_hostname]['ansible_default_ipv4']
          ['address'] }}

    - name: System {{ machine }} IPv4 address
      debug:
        msg: "{{ hostvars[machine]['ansible_default_ipv4']['address'] }}"

    - name: System {{ hosts }} uname information
      command: uname -a
      register: uname_results_1

    - debug:
        var: uname_results_1

    - name: System {{ machine }} uname information
      command: uname -a
      delegate_to: "{{ machine }}"
      register: uname_results_2

    - debug:
        var: uname_results_2