---

- hosts: "{{ hosts }}"

  tasks:
    - name: Add yum repositories
      yum_repository:
        name: "{{ item.name }}"
        description: "{{ item.description }}"
        baseurl: "{{ item.baseurl }}"
        gpgcheck: "{{ item.gpgcheck }}"
        enabled: "{{ item.enabled }}"
      loop:
        "{{ repositories }}"