---
- hosts: "{{ hosts }}"

  tasks:
    - name: User variable set?
      fail:
        msg: "User variable is undefined!"
      when: user is undefined

    - name: Machine variable set?
      fail:
        msg: "Machine variable is undefined!"
      when: machine is undefined

    - name: Get SSH public key content
      shell: cat ~/.ssh/id_rsa.pub
      changed_when: false
      register: pub_key_content

    - name: Inject SSH public key to {{ machine }} system
      authorized_key:
        user: "{{ user }}"
        state: present
        key: "{{ pub_key_content['stdout'] }}"
      delegate_to: "{{ machine }}"