---

- hosts: "{{ hosts }}"

  tasks:
    - name: Determine beaker harness repo url for RHEL >= 6
      set_fact: >
        base_url="http://beaker.engineering.redhat.com/harness/RedHatEnterpriseLinux{{ ansible_distribution_version.split('.')[0] }}"
      when: ansible_distribution == "RedHat" and ansible_distribution_version|int >= 6

    - name: Determine beaker harness repo url for RHEL == 5
      set_fact: >
        base_url="http://beaker.engineering.redhat.com/harness/RedHatEnterpriseLinuxServer{{ ansible_distribution_version.split('.')[0] }}"
      when: ansible_distribution == "RedHat" and ansible_distribution_version|int == 5

    - name: Install restraint repo
      yum_repository:
        name: restraint
        description: restraint
        baseurl: "http://bpeck.fedorapeople.org/restraint/el{{ ansible_distribution_version.split('.')[0] }}"
        gpgcheck: no
        enabled: yes

    - name: Install beaker harness repo
      yum_repository:
        name: beaker-harness
        description: Beaker harness
        baseurl: "{{ base_url }}"
        gpgcheck: no
        enabled: yes

    - name: Install beaker task repo
      yum_repository:
        name: beaker-task
        description: beaker-task
        baseurl: http://beaker.engineering.redhat.com/rpms
        gpgcheck: no
        enabled: yes

    - name: Remove conflicting packages
      yum: name={{ item }} state=absent
      loop:
        - beah
        - rhts-test-env
        - rhts-python

    - name: Install restraint on test machines
      yum: name={{ item }}
      loop:
        - restraint
        - restraint-rhts
        - staf

    - name: Install beaker packages on test machines
      yum: name={{ item }}
      loop:
        - beakerlib
        - beakerlib-redhat

    - name: Install restraint plugin to clean yum cache
      shell: |
        printf '#!/bin/sh -x\nyum clean all metadata\n' > /usr/share/restraint/plugins/completed.d/70_clear_yum_cache
        chmod a+x /usr/share/restraint/plugins/completed.d/70_clear_yum_cache

    - name: Enable restraintd service at boot
      service:
        name: restraintd
        enabled: yes

    - name: Start restraintd service
      service:
        name: restraintd
        state: started

    - name: Delay to allow restraintd deamon to start
      pause: seconds=15
