---

- hosts: "{{ hosts }}"

  tasks:
    - name: create destination directory
      file:
        path: "{{ dest }}"
        state: directory
        mode: 755
        
    - name:  retrieve the path to get the packages
      nvr_info:
        nvr: "{{ nvr }}"
        brew_root: "{{ brew_root }}"
        dest: "{{ dest }}"
        arch: "{{ ansible_architecture }}"
      register: result

    - debug: var=result

    - name: pull down the files
      shell: wget --no-check-certificate -r -nd --no-parent --reject "*.html*" {{ result.meta.data }}
      args:
        chdir: "{{ dest }}"

    - name: get all the rpm names
      find:
        paths: "{{ dest }}"
        pattern: "*.rpm"
      register: rpm_packages

    - name: install all aut rpms
      yum:
        name: "{{ item.path }}"
        state: present
      with_items: "{{ rpm_packages.files }}"
...
