---

- hosts: "{{ hosts }}"

  tasks:
    - name: Install of Rhevm Admin Server Manager ( yum -y install rhevm)
      package:
        name: rhevm
        state: present
      register: result
      until: result.rc == 0
      retries: 3
      delay: 15

    - name: Set Rhevm Answer File
      template: src=rhevm41-answer-default.j2
                dest=./rhevm-answer
      with_items:
        - { admin_fqdn: "{{ ansible_nodename }}", admin_domain: "{{ ansible_domain}}" }
      register: answer_file
    - debug: var=answer_file
 
    - name: Set Rhevm Cleanup File
      template: src=rhevm41-cleanup.j2
                dest=./rhevm-cleanup
      register: cleanup_file
    - debug: var=cleanup_file

    - name: Install of Rhevm Admin Sever Manager - engine-setup
      shell: engine-setup --config-append=rhevm-answer


