---

- hosts: "{{ hosts }}"

  tasks:
    - name: set selinux
      selinux:
        policy: targeted
        state: "{{ mode }}"
      register: selinuxResults

    - name: reboot host if needed
      shell: nohup bash -c "sleep 20s && reboot" &
      register: reboot
      when: selinuxResults.reboot_required

    - name: wait for host boot
      local_action:
        module: wait_for
        host: "{{ hostvars[inventory_hostname]['ansible_host'] }}"
        port: 22
        delay: "{{ boot_wait | default(60) }}"
        timeout: 900
        state: started
      when: reboot.changed

